### ISSUE TITLE
Install instructions unclear

### ISSUE THREAD

**Issue by Magi3r** [NyarchLinux/NyarchUpdater#1]
I already have a running nyarchlinux installation, but without the Updater preinstalled. I can't find this tool via `flatpak search updater` or `flatpak search nyarch`. Using `flatpak list` shows that your programs come from a custom origin instead of flathub. 
How do I add the custom origin for the NyarchUpdater to install it?

**Comment by FrancescoCaracciolo** [comment]
Nyarch Updater is not ready yet
